#!/bin/sh

cd .. && test -f "./ltmain.sh" || (echo "Please run this script from the scripts directory." && exit 1)

BOOST_LOCATION="/usr/"
TASKGRAPH_DIR=`pwd`
BOOST_DEST_DIR="$TASKGRAPH_DIR/boost_local"
TAR_FILE="/tmp/taskgraph_boost_headers.tar"

cd $BOOST_LOCATION &&
find $TASKGRAPH_DIR -name "*.Plo" -exec cat {} \+ | grep boost | sed -r 's/.*(include\/boost.*\.hpp).*/\1/g' | sort | uniq | xargs tar -cf $TAR_FILE &&
tar -rf $TAR_FILE include/boost/version.hpp &&
rm -rf $BOOST_DEST_DIR &&
mkdir $BOOST_DEST_DIR &&
cd $BOOST_DEST_DIR &&
tar -xf $TAR_FILE &&
echo "Copied" `tar -tf $TAR_FILE | wc -l` "headers." &&
rm $TAR_FILE
